openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: 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
omdbapi:
    url: https://www.omdbapi.com
    key: 9975420